name: WordPress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, bz2, soap, pdo_mysql, mysqli
        coverage: none

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev libpng-dev libfreetype6-dev
        sudo apt-get install -y php7.4-gd  # Adjust the PHP version as needed

    - name: Configure Composer to Allow Plugins
      run: |
        composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
        composer global require wp-coding-standards/wpcs:^3.0 --update-no-dev
        
    - name: Validate WordPress Coding Standards
      run: |
        composer global require wp-coding-standards/wpcs
        phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
        phpcs --standard=WordPress --extensions=php --ignore=*/tests/*,*/vendor/* .


    - name: Run PHPUnit Tests
      run: |
        composer install
        ./vendor/bin/phpunit 
